USE AR_IMMS;
GO

-- ============================================================
-- 1. FOREIGN KEY
-- ============================================================

-- USER_ROLE
ALTER TABLE [USER_ROLE]
ADD CONSTRAINT FK_USER_ROLE_USER
FOREIGN KEY (user_id_fk) REFERENCES [USER](user_id);

ALTER TABLE [USER_ROLE]
ADD CONSTRAINT FK_USER_ROLE_ROLE
FOREIGN KEY (role_id_fk) REFERENCES [ROLE](role_id);

-- ROOM
ALTER TABLE [ROOM]
ADD CONSTRAINT FK_ROOM_SITE
FOREIGN KEY (site_id_fk) REFERENCES [SITE](site_id);

-- RACK
ALTER TABLE [RACK]
ADD CONSTRAINT FK_RACK_ROOM
FOREIGN KEY (room_id_fk) REFERENCES [ROOM](room_id);

-- SERVER
ALTER TABLE [SERVER]
ADD CONSTRAINT FK_SERVER_RACK
FOREIGN KEY (rack_id_fk) REFERENCES [RACK](rack_id);

-- CONTAINER
ALTER TABLE [CONTAINER]
ADD CONSTRAINT FK_CONTAINER_SERVER
FOREIGN KEY (server_id_fk) REFERENCES [SERVER](server_id);

-- WARRANTY
ALTER TABLE [WARRANTY]
ADD CONSTRAINT FK_WARRANTY_SERVER
FOREIGN KEY (server_id_fk) REFERENCES [SERVER](server_id);

-- TELEMETRY (Đã sửa tham chiếu thành server_id)
ALTER TABLE [TELEMETRY]
ADD CONSTRAINT FK_TELEMETRY_SERVER
FOREIGN KEY (server_id_fk) REFERENCES [SERVER](server_id);

-- ALERT_THRESHOLD (Đã sửa tham chiếu thành server_id)
ALTER TABLE [ALERT_THRESHOLD]
ADD CONSTRAINT FK_ALERT_THRESHOLD_SERVER
FOREIGN KEY (server_id_fk) REFERENCES [SERVER](server_id);

-- ALERT (Đã sửa tham chiếu thành server_id)
ALTER TABLE [ALERT]
ADD CONSTRAINT FK_ALERT_SERVER
FOREIGN KEY (server_id_fk) REFERENCES [SERVER](server_id);

-- INCIDENT
ALTER TABLE [INCIDENT]
ADD CONSTRAINT FK_INCIDENT_ALERT
FOREIGN KEY (alert_id_fk) REFERENCES [ALERT](alert_id);

-- TICKET
ALTER TABLE [TICKET]
ADD CONSTRAINT FK_TICKET_INCIDENT
FOREIGN KEY (incident_id_fk) REFERENCES [INCIDENT](incident_id);

ALTER TABLE [TICKET]
ADD CONSTRAINT FK_TICKET_ASSIGNED_USER
FOREIGN KEY (assigned_user_id_fk) REFERENCES [USER](user_id);

-- MAINTENANCE
ALTER TABLE [MAINTENANCE]
ADD CONSTRAINT FK_MAINTENANCE_TICKET
FOREIGN KEY (ticket_id_fk) REFERENCES [TICKET](ticket_id);

-- AUDIT_LOG
ALTER TABLE [AUDIT_LOG]
ADD CONSTRAINT FK_AUDIT_LOG_USER
FOREIGN KEY (user_id_fk) REFERENCES [USER](user_id);
GO


-- ============================================================
-- 2. UNIQUE CONSTRAINT
-- ============================================================

ALTER TABLE [ROLE]
ADD CONSTRAINT UQ_ROLE_NAME UNIQUE (role_name);

ALTER TABLE [USER]
ADD CONSTRAINT UQ_USER_USERNAME UNIQUE (username);

ALTER TABLE [USER]
ADD CONSTRAINT UQ_USER_EMAIL UNIQUE (email);

ALTER TABLE [USER_ROLE]
ADD CONSTRAINT UQ_USER_ROLE UNIQUE (user_id_fk, role_id_fk);

ALTER TABLE [SITE]
ADD CONSTRAINT UQ_SITE_NAME UNIQUE (site_name);

-- SERVER (Bổ sung UNIQUE cho server_name và ip_address)
ALTER TABLE [SERVER]
ADD CONSTRAINT UQ_SERVER_NAME UNIQUE (server_name);

ALTER TABLE [SERVER]
ADD CONSTRAINT UQ_SERVER_IP UNIQUE (ip_address);

-- WARRANTY
ALTER TABLE [WARRANTY]
ADD CONSTRAINT UQ_WARRANTY_SERVER UNIQUE (server_id_fk);

-- ALERT_THRESHOLD
ALTER TABLE [ALERT_THRESHOLD]
ADD CONSTRAINT UQ_ALERT_THRESHOLD UNIQUE (server_id_fk, metric_name);
GO


-- ============================================================
-- 3. CHECK CONSTRAINT
-- ============================================================

-- USER
ALTER TABLE [USER]
ADD CONSTRAINT CK_USER_STATUS
CHECK (status IN ('ACTIVE', 'INACTIVE'));

-- SERVER
ALTER TABLE [SERVER]
ADD CONSTRAINT CK_SERVER_STATUS
CHECK (status IN ('ONLINE', 'OFFLINE', 'MAINTENANCE', 'INACTIVE'));

-- CONTAINER
ALTER TABLE [CONTAINER]
ADD CONSTRAINT CK_CONTAINER_STATUS
CHECK (status IN ('RUNNING', 'STOPPED', 'PAUSED', 'INACTIVE'));

-- WARRANTY
ALTER TABLE [WARRANTY]
ADD CONSTRAINT CK_WARRANTY_DATE
CHECK (warranty_end >= warranty_start);

-- TELEMETRY
ALTER TABLE [TELEMETRY]
ADD CONSTRAINT CK_TELEMETRY_CPU
CHECK (cpu_usage >= 0 AND cpu_usage <= 100);

ALTER TABLE [TELEMETRY]
ADD CONSTRAINT CK_TELEMETRY_RAM
CHECK (ram_usage >= 0 AND ram_usage <= 100);

ALTER TABLE [TELEMETRY]
ADD CONSTRAINT CK_TELEMETRY_DISK
CHECK (disk_usage >= 0 AND disk_usage <= 100);

-- ALERT_THRESHOLD
ALTER TABLE [ALERT_THRESHOLD]
ADD CONSTRAINT CK_THRESHOLD_VALUES
CHECK (warning_value >= 0 AND critical_value >= warning_value);

-- ALERT
ALTER TABLE [ALERT]
ADD CONSTRAINT CK_ALERT_SEVERITY
CHECK (severity IN ('WARNING', 'CRITICAL'));

ALTER TABLE [ALERT]
ADD CONSTRAINT CK_ALERT_STATUS
CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CLOSED'));

-- INCIDENT
ALTER TABLE [INCIDENT]
ADD CONSTRAINT CK_INCIDENT_PRIORITY
CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));

ALTER TABLE [INCIDENT]
ADD CONSTRAINT CK_INCIDENT_STATUS
CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'));

-- TICKET
ALTER TABLE [TICKET]
ADD CONSTRAINT CK_TICKET_PRIORITY
CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));

ALTER TABLE [TICKET]
ADD CONSTRAINT CK_TICKET_STATUS
CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'));
GO


-- ============================================================
-- 4. DEFAULT CONSTRAINT
-- ============================================================

ALTER TABLE [USER]
ADD CONSTRAINT DF_USER_STATUS DEFAULT 'Inactive' FOR status;

ALTER TABLE [SERVER]
ADD CONSTRAINT DF_SERVER_STATUS DEFAULT 'Inactive' FOR status;

ALTER TABLE [CONTAINER]
ADD CONSTRAINT DF_CONTAINER_STATUS DEFAULT 'Inactive' FOR status;

ALTER TABLE [ALERT_THRESHOLD]
ADD CONSTRAINT DF_ALERT_THRESHOLD_ACTIVE DEFAULT 1 FOR is_active;

ALTER TABLE [ALERT]
ADD CONSTRAINT DF_ALERT_STATUS DEFAULT 'OPEN' FOR status;

ALTER TABLE [ALERT]
ADD CONSTRAINT DF_ALERT_CREATED_AT DEFAULT GETDATE() FOR created_at;

ALTER TABLE [INCIDENT]
ADD CONSTRAINT DF_INCIDENT_STATUS DEFAULT 'OPEN' FOR status;

ALTER TABLE [INCIDENT]
ADD CONSTRAINT DF_INCIDENT_CREATED_AT DEFAULT GETDATE() FOR created_at;

ALTER TABLE [TICKET]
ADD CONSTRAINT DF_TICKET_STATUS DEFAULT 'OPEN' FOR status;

ALTER TABLE [TICKET]
ADD CONSTRAINT DF_TICKET_CREATED_AT DEFAULT GETDATE() FOR created_at;

ALTER TABLE [MAINTENANCE]
ADD CONSTRAINT DF_MAINTENANCE_PERFORMED_AT DEFAULT GETDATE() FOR performed_at;

ALTER TABLE [AUDIT_LOG]
ADD CONSTRAINT DF_AUDIT_LOG_CREATED_AT DEFAULT GETDATE() FOR created_at;
GO
